spring:
  messages:
    basename: i18n/login
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.56.28.200:3306/test?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    # 自定义数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # DruidDataSource 父类中存在该属性，可以进行属性绑定
    initialSize: 3
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
  jpa:
    hibernate:
      # 更新或者创建数据表
      ddl-auto: update
    # 控制台打印sql
    show-sql: true
  profiles:
    active: test
  redis:
    host: 10.56.28.200
  rabbitmq:
    host: 10.56.28.200
    username: guest
    password: guest
  elasticsearch:
    jest:
      uris: http://10.56.28.200:9201
  data:
    # SpringDataES使用的是9300端口
    elasticsearch:
      cluster-nodes: 10.56.28.200:9301
      cluster-name: elasticsearch
#项目访问路径
server:
#  context-path: /crud
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 控制台打印sql使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
neusiri:
  hello:
    name : zhangsan
# 打印日志
#logging:
    ##  level.com.neusiri.mapper: debug
management:
  context-path: /manage
  port: 8181
#debug: true # 自动配置报告